import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '../api.js';
import { FIELDS, PREMISES_CONDITIONS, DAYLIGHT_OPTIONS, FLEXIBLE_OPTIONS } from '../../src/lib/admin/model.js';
import { PROJECT_TYPES, SPACE_TYPES, SOURCES } from '../../src/lib/quoteSchema.js';

// For enquiries that arrive by phone or email. The reference is generated by the server,
// the same way as for the website form.
const KEYS = [
  'name',
  'business',
  'email',
  'phone',
  'projectType',
  'projectOther',
  'spaceType',
  'location',
  'size',
  'areas',
  'message',
  'source',
  'premisesCondition',
  'daylight',
  'flexibleTiming',
  'preferredDateTime',
  'schedulingNotes',
];

const CHOICES = {
  projectType: PROJECT_TYPES,
  spaceType: SPACE_TYPES.map((value) => ({ value, label: value })),
  source: SOURCES.map((value) => ({ value, label: value })),
  premisesCondition: PREMISES_CONDITIONS,
  daylight: DAYLIGHT_OPTIONS,
  flexibleTiming: FLEXIBLE_OPTIONS,
};

const LONG = new Set(['areas', 'message', 'schedulingNotes']);

export default function NewEnquiry() {
  const navigate = useNavigate();
  const [values, setValues] = useState(Object.fromEntries(KEYS.map((key) => [key, ''])));
  const [errors, setErrors] = useState({});
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);

  const submit = async (event) => {
    event.preventDefault();
    setBusy(true);
    setError('');
    setErrors({});
    const result = await api.create(values);
    setBusy(false);
    if (result.ok) {
      navigate(`/enquiries/${result.reference}`, { replace: true });
    } else {
      setError(result.message || 'Could not add the enquiry.');
      if (result.errors) setErrors(result.errors);
    }
  };

  return (
    <form onSubmit={submit} noValidate>
      <h1 className="ad-h1">Add an enquiry</h1>
      <p className="ad-note">
        For enquiries taken by phone or email. A ROSS reference is generated automatically.
      </p>
      {error ? (
        <p className="ad-error" role="alert">
          {error}
        </p>
      ) : null}
      <div className="ad-grid">
        {KEYS.map((key) => {
          const spec = FIELDS[key];
          const choices = CHOICES[key];
          const id = `new-${key}`;
          return (
            <div className="ad-field" key={key}>
              <label className="ad-label" htmlFor={id}>
                {spec.label}
              </label>
              {choices ? (
                <select
                  id={id}
                  className="ad-input"
                  value={values[key]}
                  onChange={(event) => setValues({ ...values, [key]: event.target.value })}
                >
                  <option value="">Not set</option>
                  {choices.map((option) => (
                    <option key={option.value} value={option.value}>
                      {option.label}
                    </option>
                  ))}
                </select>
              ) : LONG.has(key) ? (
                <textarea
                  id={id}
                  className="ad-input ad-input--area"
                  rows={4}
                  value={values[key]}
                  onChange={(event) => setValues({ ...values, [key]: event.target.value })}
                />
              ) : (
                <input
                  id={id}
                  className="ad-input"
                  type={spec.type === 'email' ? 'email' : 'text'}
                  value={values[key]}
                  onChange={(event) => setValues({ ...values, [key]: event.target.value })}
                />
              )}
              {errors[key] ? <span className="ad-field__error">{errors[key]}</span> : null}
            </div>
          );
        })}
      </div>
      <button className="ad-button" type="submit" disabled={busy}>
        {busy ? 'Adding…' : 'Add enquiry'}
      </button>
    </form>
  );
}
